Update Traditional Chinese (zh_tw.json)
henkelmax/simple-voice-chat pull request #722
Opened 2024-08-08 11:23 UTC by yichifauzi

Update and Fix Traditional Chinese localization

2024-08-19 14:38 UTC, notlin4 requested changes

2024-08-19 14:38 UTC, notlin4 commented on common/src/main/resources/assets/voicechat/lang/zh_tw.json
> +  "cloth_config.voicechat.config.run_local_server": "在單人遊戲或區域網世界中執行",
```suggestion
  "cloth_config.voicechat.config.run_local_server": "在單人遊戲或區域網路世界中執行",
```

2024-08-19 14:38 UTC, notlin4 commented on common/src/main/resources/assets/voicechat/lang/zh_tw.json
> +  "cloth_config.voicechat.config.run_local_server.description": "語音聊天室否於單人遊戲或區域網世界中執行",
```suggestion
  "cloth_config.voicechat.config.run_local_server.description": "語音聊天室是否應於單人遊戲或區域網路世界中執行",
```

2024-09-12 11:09 UTC, merged

2024-09-12 11:09 UTC, henkelmax commented
Thank you!